/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

public class frmPrincipalUser extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public frmPrincipalUser() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        casilla_logo = new javax.swing.JPanel();
        ico_logo_40x40 = new javax.swing.JLabel();
        txt_proyecto = new javax.swing.JLabel();
        txt_empresa = new javax.swing.JLabel();
        btn_cerrar_sesion_txt = new javax.swing.JButton();
        btn_cerrar_sesion_ico = new javax.swing.JButton();
        casilla_perfil = new javax.swing.JPanel();
        txt_sabs = new javax.swing.JLabel();
        ico_foto_80x80 = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JLabel();
        txt_nombre_usuario = new javax.swing.JLabel();
        txt_acceso = new javax.swing.JLabel();
        txt_usuario = new javax.swing.JLabel();
        casilla_servicios = new javax.swing.JPanel();
        ico_donantes_62x62 = new javax.swing.JLabel();
        btn_donantes = new javax.swing.JButton();
        txt_donantes = new javax.swing.JTextArea();
        btn_solicitudes = new javax.swing.JButton();
        ico_solicitudes_62x62 = new javax.swing.JLabel();
        txt_solicitudes = new javax.swing.JTextArea();
        ico_extracciones_62x62 = new javax.swing.JLabel();
        btn_extracciones = new javax.swing.JButton();
        txt_extracciones = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SABS");
        setBackground(new java.awt.Color(243, 95, 95));
        setSize(new java.awt.Dimension(520, 300));

        casilla_logo.setBackground(new java.awt.Color(243, 95, 95));
        casilla_logo.setPreferredSize(new java.awt.Dimension(50, 0));

        ico_logo_40x40.setBackground(new java.awt.Color(255, 204, 204));
        ico_logo_40x40.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ico_logo_40x40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/SABS_Logo_50x50.png"))); // NOI18N

        txt_proyecto.setBackground(new java.awt.Color(255, 255, 255));
        txt_proyecto.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        txt_proyecto.setForeground(new java.awt.Color(255, 255, 255));
        txt_proyecto.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txt_proyecto.setText("SISTEMA DE ADMINISTRACIÓN DEL BANCO DE SANGRE");

        txt_empresa.setBackground(new java.awt.Color(255, 255, 255));
        txt_empresa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_empresa.setForeground(new java.awt.Color(255, 204, 204));
        txt_empresa.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txt_empresa.setText("Blood Care Bank");

        btn_cerrar_sesion_txt.setForeground(new java.awt.Color(255, 204, 204));
        btn_cerrar_sesion_txt.setText("Cerrar Sesión  ");
        btn_cerrar_sesion_txt.setBorder(null);
        btn_cerrar_sesion_txt.setBorderPainted(false);
        btn_cerrar_sesion_txt.setContentAreaFilled(false);
        btn_cerrar_sesion_txt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_cerrar_sesion_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cerrar_sesion_txtActionPerformed(evt);
            }
        });

        btn_cerrar_sesion_ico.setBackground(new java.awt.Color(243, 95, 95));
        btn_cerrar_sesion_ico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/SABS_CerrarSesion_20x20.png"))); // NOI18N
        btn_cerrar_sesion_ico.setBorder(null);
        btn_cerrar_sesion_ico.setBorderPainted(false);
        btn_cerrar_sesion_ico.setContentAreaFilled(false);
        btn_cerrar_sesion_ico.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_cerrar_sesion_ico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cerrar_sesion_icoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout casilla_logoLayout = new javax.swing.GroupLayout(casilla_logo);
        casilla_logo.setLayout(casilla_logoLayout);
        casilla_logoLayout.setHorizontalGroup(
            casilla_logoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, casilla_logoLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(ico_logo_40x40, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(casilla_logoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_proyecto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, casilla_logoLayout.createSequentialGroup()
                        .addComponent(txt_empresa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_cerrar_sesion_txt)
                        .addGap(0, 0, 0)
                        .addComponent(btn_cerrar_sesion_ico, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        casilla_logoLayout.setVerticalGroup(
            casilla_logoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(casilla_logoLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(casilla_logoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ico_logo_40x40, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(casilla_logoLayout.createSequentialGroup()
                        .addComponent(txt_proyecto)
                        .addGap(10, 10, 10)
                        .addGroup(casilla_logoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(casilla_logoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txt_empresa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_cerrar_sesion_txt))
                            .addComponent(btn_cerrar_sesion_ico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(17, 17, 17))
        );

        casilla_perfil.setBackground(new java.awt.Color(255, 204, 204));

        txt_sabs.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        txt_sabs.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_sabs.setText("SABS");

        ico_foto_80x80.setBackground(new java.awt.Color(255, 204, 204));
        ico_foto_80x80.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ico_foto_80x80.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/SABS_FotoPerfil_80x80.png"))); // NOI18N

        txt_nombre.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_nombre.setText("Nombre:");

        txt_nombre_usuario.setBackground(new java.awt.Color(255, 255, 255));
        txt_nombre_usuario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_nombre_usuario.setForeground(new java.awt.Color(243, 95, 95));
        txt_nombre_usuario.setText("tu_nombre");

        txt_acceso.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_acceso.setText("Acceso:");

        txt_usuario.setBackground(new java.awt.Color(255, 255, 255));
        txt_usuario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_usuario.setForeground(new java.awt.Color(243, 95, 95));
        txt_usuario.setText("Usuario");

        javax.swing.GroupLayout casilla_perfilLayout = new javax.swing.GroupLayout(casilla_perfil);
        casilla_perfil.setLayout(casilla_perfilLayout);
        casilla_perfilLayout.setHorizontalGroup(
            casilla_perfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(casilla_perfilLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(casilla_perfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_acceso)
                    .addComponent(txt_nombre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(casilla_perfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_nombre_usuario, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                    .addComponent(txt_usuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20))
            .addGroup(casilla_perfilLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(casilla_perfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ico_foto_80x80, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_sabs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        casilla_perfilLayout.setVerticalGroup(
            casilla_perfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(casilla_perfilLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(txt_sabs)
                .addGap(11, 11, 11)
                .addComponent(ico_foto_80x80, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addGroup(casilla_perfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_nombre)
                    .addComponent(txt_nombre_usuario))
                .addGap(11, 11, 11)
                .addGroup(casilla_perfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_acceso)
                    .addComponent(txt_usuario))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        casilla_servicios.setBackground(new java.awt.Color(255, 255, 255));
        casilla_servicios.setPreferredSize(new java.awt.Dimension(520, 297));

        ico_donantes_62x62.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/SABS_Donantes_62x62.png"))); // NOI18N

        btn_donantes.setBackground(new java.awt.Color(255, 204, 204));
        btn_donantes.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_donantes.setForeground(new java.awt.Color(243, 95, 95));
        btn_donantes.setText("REGISTRAR DONANTE");
        btn_donantes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        txt_donantes.setEditable(false);
        txt_donantes.setBackground(new java.awt.Color(255, 255, 255));
        txt_donantes.setColumns(20);
        txt_donantes.setLineWrap(true);
        txt_donantes.setRows(2);
        txt_donantes.setText("- Añade nuevos donantes de sangre.\n- Edita o elimina donantes registrados.");
        txt_donantes.setWrapStyleWord(true);

        btn_solicitudes.setBackground(new java.awt.Color(255, 204, 204));
        btn_solicitudes.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_solicitudes.setForeground(new java.awt.Color(243, 95, 95));
        btn_solicitudes.setText("REGISTRAR SOLICITUD");
        btn_solicitudes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_solicitudes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_solicitudesActionPerformed(evt);
            }
        });

        ico_solicitudes_62x62.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/SABS_Solicitudes_62x62.png"))); // NOI18N

        txt_solicitudes.setEditable(false);
        txt_solicitudes.setBackground(new java.awt.Color(255, 255, 255));
        txt_solicitudes.setColumns(20);
        txt_solicitudes.setLineWrap(true);
        txt_solicitudes.setRows(2);
        txt_solicitudes.setText("- Añade nuevas solicitudes de sangre.\n- Edita o elimina solicitudes registradas.");
        txt_solicitudes.setWrapStyleWord(true);

        ico_extracciones_62x62.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/SABS_Extraccion_62x62.png"))); // NOI18N

        btn_extracciones.setBackground(new java.awt.Color(255, 204, 204));
        btn_extracciones.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_extracciones.setForeground(new java.awt.Color(243, 95, 95));
        btn_extracciones.setText("REGISTRAR EXTRACCIÓN");
        btn_extracciones.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_extracciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_extraccionesActionPerformed(evt);
            }
        });

        txt_extracciones.setEditable(false);
        txt_extracciones.setBackground(new java.awt.Color(255, 255, 255));
        txt_extracciones.setColumns(20);
        txt_extracciones.setLineWrap(true);
        txt_extracciones.setRows(2);
        txt_extracciones.setText("- Añade nuevas extracciones de sangre.\n- Edita o elimina extracciones registradas.");
        txt_extracciones.setWrapStyleWord(true);

        javax.swing.GroupLayout casilla_serviciosLayout = new javax.swing.GroupLayout(casilla_servicios);
        casilla_servicios.setLayout(casilla_serviciosLayout);
        casilla_serviciosLayout.setHorizontalGroup(
            casilla_serviciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(casilla_serviciosLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(casilla_serviciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(ico_donantes_62x62, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ico_solicitudes_62x62, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ico_extracciones_62x62, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10)
                .addGroup(casilla_serviciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_extracciones)
                    .addComponent(btn_extracciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_solicitudes)
                    .addComponent(btn_solicitudes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_donantes)
                    .addComponent(btn_donantes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18))
        );
        casilla_serviciosLayout.setVerticalGroup(
            casilla_serviciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(casilla_serviciosLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(casilla_serviciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ico_donantes_62x62, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(casilla_serviciosLayout.createSequentialGroup()
                        .addComponent(btn_donantes)
                        .addGap(0, 0, 0)
                        .addComponent(txt_donantes, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(11, 11, 11)
                .addGroup(casilla_serviciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ico_solicitudes_62x62, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(casilla_serviciosLayout.createSequentialGroup()
                        .addComponent(btn_solicitudes)
                        .addGap(0, 0, 0)
                        .addComponent(txt_solicitudes, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(11, 11, 11)
                .addGroup(casilla_serviciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(casilla_serviciosLayout.createSequentialGroup()
                        .addComponent(btn_extracciones)
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(txt_extracciones, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ico_extracciones_62x62))
                .addGap(11, 11, 11))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(casilla_perfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(casilla_servicios, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE))
            .addComponent(casilla_logo, javax.swing.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(casilla_logo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(casilla_perfil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(casilla_servicios, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cerrar_sesion_icoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cerrar_sesion_icoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_cerrar_sesion_icoActionPerformed

    private void btn_extraccionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_extraccionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_extraccionesActionPerformed

    private void btn_solicitudesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_solicitudesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_solicitudesActionPerformed

    private void btn_cerrar_sesion_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cerrar_sesion_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_cerrar_sesion_txtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrincipalUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrincipalUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrincipalUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrincipalUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPrincipalUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn_cerrar_sesion_ico;
    public javax.swing.JButton btn_cerrar_sesion_txt;
    public javax.swing.JButton btn_donantes;
    public javax.swing.JButton btn_extracciones;
    public javax.swing.JButton btn_solicitudes;
    public javax.swing.JPanel casilla_logo;
    public javax.swing.JPanel casilla_perfil;
    public javax.swing.JPanel casilla_servicios;
    private javax.swing.JLabel ico_donantes_62x62;
    private javax.swing.JLabel ico_extracciones_62x62;
    public javax.swing.JLabel ico_foto_80x80;
    public javax.swing.JLabel ico_logo_40x40;
    private javax.swing.JLabel ico_solicitudes_62x62;
    private javax.swing.JLabel txt_acceso;
    private javax.swing.JTextArea txt_donantes;
    private javax.swing.JLabel txt_empresa;
    private javax.swing.JTextArea txt_extracciones;
    private javax.swing.JLabel txt_nombre;
    public javax.swing.JLabel txt_nombre_usuario;
    private javax.swing.JLabel txt_proyecto;
    private javax.swing.JLabel txt_sabs;
    private javax.swing.JTextArea txt_solicitudes;
    public javax.swing.JLabel txt_usuario;
    // End of variables declaration//GEN-END:variables
}
